from __future__ import annotations

STANDARD_AMINO_ACIDS = frozenset("ACDEFGHIKLMNPQRSTVWY")
STANDARD_AMINO_ACID_ORDER = "ACDEFGHIKLMNPQRSTVWY"
MIN_LENGTH = 8
MAX_LENGTH = 50
DEFAULT_LIBRARY_SIZE = 50_000
DEFAULT_TOP_SIZE = 100
DEFAULT_SEED = 42
DEFAULT_REFERENCE = "data/antibacterial.fasta"
DEFAULT_CONFIG = "configs/default.json"
